# Generated by Django 5.2.17 on 2026-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ee', 'EE module'), ('cs', 'CS module')], max_length=2)),
                ('difficulty', models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('simple', 'Simple')], max_length=6, verbose_name='Exam difficulty')),
                ('exam_form', models.CharField(choices=[('open', 'Open Book'), ('closed', 'Close Book'), ('report', 'Just Representation/Report'), ('oral', 'Oral Exam')], max_length=6)),
                ('description', models.TextField(max_length=5000)),
                ('semester', models.CharField(choices=[('winter', 'Winter semester'), ('summer', 'Summer semester')], max_length=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
    ]

