# Generated by Django 5.2.17 on 2026-10-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity_limited',
            field=models.BooleanField(default=False, verbose_name='Capacity limited'),
        ),
    ]

