# Generated by Django 5.2.17 on 2026-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_capacity_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', models.TextField(max_length=10000, verbose_name='Body')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Website name')),
                ('url', models.URLField(max_length=2000, verbose_name='Website URL')),
                ('description', models.TextField(max_length=5000, verbose_name='Description')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]

