# Generated by Django 5.2.17 on 2026-10-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tip_usefullink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ee', 'EE module'), ('cs', 'CS module'), ('seminar', 'Seminar'), ('lab', 'Lab'), ('non-tech', 'Non-tech'), ('basic', 'Basic')], max_length=8),
        ),
    ]
