# Generated by Django 5.2.17 on 2026-09-29 13:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def mark_existing_articles(apps, schema_editor):
    from django.utils import timezone
    Article = apps.get_model('blog', 'Article')
    Article.objects.filter(status='published', published_at__lte=timezone.now()).update(notification_sent_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_body_alter_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('articles', models.BooleanField(default=True, verbose_name='新文章通知')),
                ('discussions', models.BooleanField(default=True, verbose_name='讨论更新通知')),
                ('replies', models.BooleanField(default=True, verbose_name='回复通知')),
                ('language', models.CharField(choices=[('zh', '中文'), ('en', 'English')], default='zh', max_length=2)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '订阅读者',
                'verbose_name_plural': '订阅读者',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='blog.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.subscriber'),
        ),
        migrations.CreateModel(
            name='SubscriberLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('language', models.CharField(default='zh', max_length=2)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='话题')),
                ('author', models.CharField(max_length=80, verbose_name='发起人')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='内容（Markdown）')),
                ('visible', models.BooleanField(default=True, verbose_name='公开显示')),
                ('locked', models.BooleanField(default=False, verbose_name='关闭回复')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subscriber')),
            ],
            options={
                'verbose_name': '讨论话题',
                'verbose_name_plural': '讨论话题',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='blog.discussionpost')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subscriber')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.topic')),
            ],
            options={
                'verbose_name': '讨论回复',
                'verbose_name_plural': '讨论回复',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('articles', '新文章'), ('discussions', '讨论更新'), ('replies', '回复')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('cancelled', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.discussionpost')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subscriber')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topic')),
            ],
            options={
                'verbose_name': '邮件通知',
                'verbose_name_plural': '邮件通知',
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'event_key'), name='unique_notification_recipient_event')],
            },
        ),
        migrations.RunPython(mark_existing_articles, migrations.RunPython.noop),
    ]
