# Generated by Django 5.2.17 on 2026-09-29 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscriber_article_notification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='delivery_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriberlogin',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
